# starts all the components of the POC
version: '3.7'
services:
  cs-ops:
    build: ./cs-customOps
    init: true
    ports:
      - 9300:9300
    environment:
      - LOGDB=mongo-log
      - SERVERBASE=http://hapi-data:8080/fhir/
    networks:
      - poc-net
  cs-ui:
    build: ./cs-UI-request-lab1
    init: true
    ports:
      - 9500:9500
    environment:
      - LOGDB=mongo-log
      - SERVERBASE=http://hapi-data:8080/fhir/
    networks:
      - poc-net
  mongo-log:
    image: mongo:latest
    networks:
      - poc-net
    # ports:    don't allow access to log outside the docker network
    #  - 27017:27017
  hapi-data:
    image: hapiproject/hapi
    ports:
      - 8080:8080
    networks:
      - poc-net
networks:
  poc-net:
    
