version: '3.7'

# run the support containers only
services:

  mongo-log:
    image: mongo:latest
    networks:
      - poc-net
    ports:  
      - 27017:27017
  hapi-data:
    image: hapiproject/hapi
    ports:
      - 8080:8080
    networks:
      - poc-net
  #hapi-conformance:
  #  image: hapiproject/hapi
  #  ports:
  #    - 8091:8080
  #  networks:
  #    - poc-net
networks:
  poc-net:
    
