FROM nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

#COPY nginx.conf /etc/nginx/nginx.conf

# https://www.guyrking.com/2019/10/20/configure-run-and-test-nginx-on-localhost.html

# docker image build --tag cs-nginx .
# docker run --name myNginx -p 3000:3000 cs-nginx